name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Passo para fazer o checkout do repositório
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Passo para instalar as dependências do projeto
      - name: Install Dependencies
        run: npm install

      - name: Install Yarn Dependencies
        run: npm run yarn

      # Passo para rodar o build do projeto Quasar
      - name: Build the project
        run: npm run build

      # Passo para fazer o deploy para Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_FOREST_05F747F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integrações com GitHub (comentários em PR, etc.)
          action: "upload"
          ###### Configurações de Repositório/Build ######
          app_location: "/" # Caminho do código-fonte do App
          api_location: "" # Caminho do código-fonte da API - opcional
          output_location: "dist/spa" # Diretório de conteúdo do app compilado
          ###### Fim das Configurações de Repositório/Build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_FOREST_05F747F1E }}
          action: "close"
